# Generated by Django 5.2.5 on 2025-09-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField()),
                ('car_no', models.IntegerField()),
                ('release_date', models.DateField()),
                ('car_colour', models.CharField()),
            ],
        ),
    ]
